# Generated by Django 6.1 on 2026-09-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=100, verbose_name='Paciente')),
                ('medico', models.CharField(max_length=100, verbose_name='Médico')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20, verbose_name='Estado')),
            ],
        ),
    ]
